// GENERATED by tools/gen-xwire - do not edit
//
// x11 wire codecs, native endian: the setup handshake declares host
// byte order, so to_ne_bytes is correct by construction.
//
// the surface is generated ahead of use, so dead-code lints are noise
#![allow(dead_code)]

fn begin(b: &mut Vec<u8>, major: u8, detail: u8) -> usize {
    let start = b.len();
    b.push(major);
    b.push(detail);
    b.extend_from_slice(&0u16.to_ne_bytes());
    start
}

fn finish(b: &mut Vec<u8>, start: usize) {
    while (b.len() - start) % 4 != 0 {
        b.push(0);
    }
    let units = ((b.len() - start) / 4) as u16;
    b[start + 2..start + 4].copy_from_slice(&units.to_ne_bytes());
}

// x value-lists: ascending bit order, one u32 per set bit
fn push_values(b: &mut Vec<u8>, values: &[(u8, u32)]) -> u32 {
    let mut sorted: Vec<(u8, u32)> = values.to_vec();
    sorted.sort_by_key(|v| v.0);
    let mut mask = 0u32;
    for (bit, _) in &sorted {
        mask |= 1 << bit;
    }
    for (_, v) in &sorted {
        b.extend_from_slice(&v.to_ne_bytes());
    }
    mask
}

fn u16at(f: &[u8], o: usize) -> u16 {
    u16::from_ne_bytes([f[o], f[o + 1]])
}

fn i16at(f: &[u8], o: usize) -> i16 {
    i16::from_ne_bytes([f[o], f[o + 1]])
}

fn u32at(f: &[u8], o: usize) -> u32 {
    u32::from_ne_bytes([f[o], f[o + 1], f[o + 2], f[o + 3]])
}

// -- core requests --

pub fn create_window(b: &mut Vec<u8>, depth: u8, wid: u32, parent: u32, x: i16, y: i16, width: u16, height: u16, border_width: u16, class: u16, visual: u32, values: &[(u8, u32)]) {
    let s = begin(b, 1, depth);
    b.extend_from_slice(&wid.to_ne_bytes());
    b.extend_from_slice(&parent.to_ne_bytes());
    b.extend_from_slice(&x.to_ne_bytes());
    b.extend_from_slice(&y.to_ne_bytes());
    b.extend_from_slice(&width.to_ne_bytes());
    b.extend_from_slice(&height.to_ne_bytes());
    b.extend_from_slice(&border_width.to_ne_bytes());
    b.extend_from_slice(&class.to_ne_bytes());
    b.extend_from_slice(&visual.to_ne_bytes());
    let mp = b.len();
    b.extend_from_slice(&[0u8; 4]);
    let mask = push_values(b, values);
    b[mp..mp + 4].copy_from_slice(&mask.to_ne_bytes());
    finish(b, s);
}

pub fn change_window_attributes(b: &mut Vec<u8>, window: u32, values: &[(u8, u32)]) {
    let s = begin(b, 2, 0);
    b.extend_from_slice(&window.to_ne_bytes());
    let mp = b.len();
    b.extend_from_slice(&[0u8; 4]);
    let mask = push_values(b, values);
    b[mp..mp + 4].copy_from_slice(&mask.to_ne_bytes());
    finish(b, s);
}

pub fn map_window(b: &mut Vec<u8>, window: u32) {
    let s = begin(b, 8, 0);
    b.extend_from_slice(&window.to_ne_bytes());
    finish(b, s);
}

pub fn get_geometry(b: &mut Vec<u8>, drawable: u32) {
    let s = begin(b, 14, 0);
    b.extend_from_slice(&drawable.to_ne_bytes());
    finish(b, s);
}

pub fn get_atom_name(b: &mut Vec<u8>, atom: u32) {
    let s = begin(b, 17, 0);
    b.extend_from_slice(&atom.to_ne_bytes());
    finish(b, s);
}

pub fn get_property(b: &mut Vec<u8>, delete: u8, window: u32, property: u32, ty: u32, long_offset: u32, long_length: u32) {
    let s = begin(b, 20, delete);
    b.extend_from_slice(&window.to_ne_bytes());
    b.extend_from_slice(&property.to_ne_bytes());
    b.extend_from_slice(&ty.to_ne_bytes());
    b.extend_from_slice(&long_offset.to_ne_bytes());
    b.extend_from_slice(&long_length.to_ne_bytes());
    finish(b, s);
}

pub fn set_selection_owner(b: &mut Vec<u8>, owner: u32, selection: u32, time: u32) {
    let s = begin(b, 22, 0);
    b.extend_from_slice(&owner.to_ne_bytes());
    b.extend_from_slice(&selection.to_ne_bytes());
    b.extend_from_slice(&time.to_ne_bytes());
    finish(b, s);
}

pub fn convert_selection(b: &mut Vec<u8>, requestor: u32, selection: u32, target: u32, property: u32, time: u32) {
    let s = begin(b, 24, 0);
    b.extend_from_slice(&requestor.to_ne_bytes());
    b.extend_from_slice(&selection.to_ne_bytes());
    b.extend_from_slice(&target.to_ne_bytes());
    b.extend_from_slice(&property.to_ne_bytes());
    b.extend_from_slice(&time.to_ne_bytes());
    finish(b, s);
}

pub fn set_input_focus(b: &mut Vec<u8>, revert_to: u8, focus: u32, time: u32) {
    let s = begin(b, 42, revert_to);
    b.extend_from_slice(&focus.to_ne_bytes());
    b.extend_from_slice(&time.to_ne_bytes());
    finish(b, s);
}

pub fn get_input_focus(b: &mut Vec<u8>) {
    let s = begin(b, 43, 0);
    finish(b, s);
}

pub fn create_pixmap(b: &mut Vec<u8>, depth: u8, pid: u32, drawable: u32, width: u16, height: u16) {
    let s = begin(b, 53, depth);
    b.extend_from_slice(&pid.to_ne_bytes());
    b.extend_from_slice(&drawable.to_ne_bytes());
    b.extend_from_slice(&width.to_ne_bytes());
    b.extend_from_slice(&height.to_ne_bytes());
    finish(b, s);
}

pub fn free_pixmap(b: &mut Vec<u8>, pixmap: u32) {
    let s = begin(b, 54, 0);
    b.extend_from_slice(&pixmap.to_ne_bytes());
    finish(b, s);
}

pub fn create_gc(b: &mut Vec<u8>, cid: u32, drawable: u32, values: &[(u8, u32)]) {
    let s = begin(b, 55, 0);
    b.extend_from_slice(&cid.to_ne_bytes());
    b.extend_from_slice(&drawable.to_ne_bytes());
    let mp = b.len();
    b.extend_from_slice(&[0u8; 4]);
    let mask = push_values(b, values);
    b[mp..mp + 4].copy_from_slice(&mask.to_ne_bytes());
    finish(b, s);
}

pub fn free_gc(b: &mut Vec<u8>, gc: u32) {
    let s = begin(b, 60, 0);
    b.extend_from_slice(&gc.to_ne_bytes());
    finish(b, s);
}

pub fn create_cursor(b: &mut Vec<u8>, cid: u32, source: u32, mask: u32, fore_red: u16, fore_green: u16, fore_blue: u16, back_red: u16, back_green: u16, back_blue: u16, x: u16, y: u16) {
    let s = begin(b, 93, 0);
    b.extend_from_slice(&cid.to_ne_bytes());
    b.extend_from_slice(&source.to_ne_bytes());
    b.extend_from_slice(&mask.to_ne_bytes());
    b.extend_from_slice(&fore_red.to_ne_bytes());
    b.extend_from_slice(&fore_green.to_ne_bytes());
    b.extend_from_slice(&fore_blue.to_ne_bytes());
    b.extend_from_slice(&back_red.to_ne_bytes());
    b.extend_from_slice(&back_green.to_ne_bytes());
    b.extend_from_slice(&back_blue.to_ne_bytes());
    b.extend_from_slice(&x.to_ne_bytes());
    b.extend_from_slice(&y.to_ne_bytes());
    finish(b, s);
}

pub fn list_extensions(b: &mut Vec<u8>) {
    let s = begin(b, 99, 0);
    finish(b, s);
}

pub fn kill_client(b: &mut Vec<u8>, resource: u32) {
    let s = begin(b, 113, 0);
    b.extend_from_slice(&resource.to_ne_bytes());
    finish(b, s);
}

// configure window carries a u16 mask with 2 bytes of pad
pub fn configure_window(b: &mut Vec<u8>, window: u32, values: &[(u8, u32)]) {
    let s = begin(b, 12, 0);
    b.extend_from_slice(&window.to_ne_bytes());
    let mp = b.len();
    b.extend_from_slice(&[0u8; 4]);
    let mask = push_values(b, values) as u16;
    b[mp..mp + 2].copy_from_slice(&mask.to_ne_bytes());
    finish(b, s);
}

pub fn intern_atom(b: &mut Vec<u8>, only_if_exists: bool, name: &[u8]) {
    let s = begin(b, 16, only_if_exists as u8);
    b.extend_from_slice(&(name.len() as u16).to_ne_bytes());
    b.extend_from_slice(&[0u8; 2]);
    b.extend_from_slice(name);
    finish(b, s);
}

pub fn query_extension(b: &mut Vec<u8>, name: &[u8]) {
    let s = begin(b, 98, 0);
    b.extend_from_slice(&(name.len() as u16).to_ne_bytes());
    b.extend_from_slice(&[0u8; 2]);
    b.extend_from_slice(name);
    finish(b, s);
}

// data_len is in format-sized units; data is raw bytes
pub fn change_property(
    b: &mut Vec<u8>,
    mode: u8,
    window: u32,
    property: u32,
    ty: u32,
    format: u8,
    data: &[u8],
) {
    let s = begin(b, 18, mode);
    b.extend_from_slice(&window.to_ne_bytes());
    b.extend_from_slice(&property.to_ne_bytes());
    b.extend_from_slice(&ty.to_ne_bytes());
    b.push(format);
    b.extend_from_slice(&[0u8; 3]);
    let units = data.len() as u32 / (format as u32 / 8).max(1);
    b.extend_from_slice(&units.to_ne_bytes());
    b.extend_from_slice(data);
    finish(b, s);
}

pub fn put_image(
    b: &mut Vec<u8>,
    format: u8,
    drawable: u32,
    gc: u32,
    width: u16,
    height: u16,
    dst_x: i16,
    dst_y: i16,
    depth: u8,
    data: &[u8],
) {
    let s = begin(b, 72, format);
    b.extend_from_slice(&drawable.to_ne_bytes());
    b.extend_from_slice(&gc.to_ne_bytes());
    b.extend_from_slice(&width.to_ne_bytes());
    b.extend_from_slice(&height.to_ne_bytes());
    b.extend_from_slice(&dst_x.to_ne_bytes());
    b.extend_from_slice(&dst_y.to_ne_bytes());
    b.push(0); // left_pad
    b.push(depth);
    b.extend_from_slice(&[0u8; 2]);
    b.extend_from_slice(data);
    finish(b, s);
}

pub fn send_event(b: &mut Vec<u8>, propagate: bool, destination: u32, event_mask: u32, event: &[u8; 32]) {
    let s = begin(b, 25, propagate as u8);
    b.extend_from_slice(&destination.to_ne_bytes());
    b.extend_from_slice(&event_mask.to_ne_bytes());
    b.extend_from_slice(event);
    finish(b, s);
}

// -- extension requests --

pub fn composite_redirect_subwindows(b: &mut Vec<u8>, major: u8, window: u32, update: u8) {
    let s = begin(b, major, 2);
    b.extend_from_slice(&window.to_ne_bytes());
    b.push(update);
    b.extend_from_slice(&[0u8; 3]);
    finish(b, s);
}

pub fn xfixes_query_version(b: &mut Vec<u8>, major: u8, client_major: u32, client_minor: u32) {
    let s = begin(b, major, 0);
    b.extend_from_slice(&client_major.to_ne_bytes());
    b.extend_from_slice(&client_minor.to_ne_bytes());
    finish(b, s);
}

pub fn xfixes_select_selection_input(b: &mut Vec<u8>, major: u8, window: u32, selection: u32, event_mask: u32) {
    let s = begin(b, major, 2);
    b.extend_from_slice(&window.to_ne_bytes());
    b.extend_from_slice(&selection.to_ne_bytes());
    b.extend_from_slice(&event_mask.to_ne_bytes());
    finish(b, s);
}

pub fn render_query_pict_formats(b: &mut Vec<u8>, major: u8) {
    let s = begin(b, major, 1);
    finish(b, s);
}

pub fn render_create_picture(b: &mut Vec<u8>, major: u8, pid: u32, drawable: u32, format: u32, values: &[(u8, u32)]) {
    let s = begin(b, major, 4);
    b.extend_from_slice(&pid.to_ne_bytes());
    b.extend_from_slice(&drawable.to_ne_bytes());
    b.extend_from_slice(&format.to_ne_bytes());
    let mp = b.len();
    b.extend_from_slice(&[0u8; 4]);
    let mask = push_values(b, values);
    b[mp..mp + 4].copy_from_slice(&mask.to_ne_bytes());
    finish(b, s);
}

pub fn render_create_cursor(b: &mut Vec<u8>, major: u8, cid: u32, source: u32, x: u16, y: u16) {
    let s = begin(b, major, 27);
    b.extend_from_slice(&cid.to_ne_bytes());
    b.extend_from_slice(&source.to_ne_bytes());
    b.extend_from_slice(&x.to_ne_bytes());
    b.extend_from_slice(&y.to_ne_bytes());
    finish(b, s);
}

pub fn res_query_client_ids(b: &mut Vec<u8>, major: u8, specs: &[(u32, u32)]) {
    let s = begin(b, major, 4);
    b.extend_from_slice(&(specs.len() as u32).to_ne_bytes());
    for (client, mask) in specs {
        b.extend_from_slice(&client.to_ne_bytes());
        b.extend_from_slice(&mask.to_ne_bytes());
    }
    finish(b, s);
}

// -- replies --
// input is the whole frame: 32 byte header plus extra_len * 4 bytes

pub fn reply_extra_len(header: &[u8]) -> usize {
    u32at(header, 4) as usize * 4
}

pub struct GetInputFocusReply {
    pub revert_to: u8,
    pub focus: u32,
}

pub fn parse_get_input_focus(f: &[u8]) -> Option<GetInputFocusReply> {
    if f.len() < 32 {
        return None;
    }
    Some(GetInputFocusReply { revert_to: f[1], focus: u32at(f, 8) })
}

pub fn parse_intern_atom(f: &[u8]) -> Option<u32> {
    if f.len() < 32 {
        return None;
    }
    Some(u32at(f, 8))
}

pub fn parse_get_atom_name(f: &[u8]) -> Option<String> {
    if f.len() < 32 {
        return None;
    }
    let len = u16at(f, 8) as usize;
    let name = f.get(32..32 + len)?;
    Some(String::from_utf8_lossy(name).into_owned())
}

pub struct GetGeometryReply {
    pub depth: u8,
    pub root: u32,
    pub x: i16,
    pub y: i16,
    pub width: u16,
    pub height: u16,
    pub border_width: u16,
}

pub fn parse_get_geometry(f: &[u8]) -> Option<GetGeometryReply> {
    if f.len() < 32 {
        return None;
    }
    Some(GetGeometryReply {
        depth: f[1],
        root: u32at(f, 8),
        x: i16at(f, 12),
        y: i16at(f, 14),
        width: u16at(f, 16),
        height: u16at(f, 18),
        border_width: u16at(f, 20),
    })
}

pub struct GetPropertyReply {
    pub format: u8,
    pub ty: u32,
    pub bytes_after: u32,
    pub data: Vec<u8>,
}

pub fn parse_get_property(f: &[u8]) -> Option<GetPropertyReply> {
    if f.len() < 32 {
        return None;
    }
    let format = f[1];
    let value_len = u32at(f, 16) as usize;
    let bytes = value_len * (format as usize / 8).max(if format == 0 { 0 } else { 1 });
    let data = f.get(32..32 + bytes)?.to_vec();
    Some(GetPropertyReply { format, ty: u32at(f, 8), bytes_after: u32at(f, 12), data })
}

pub struct QueryExtensionReply {
    pub present: bool,
    pub major_opcode: u8,
    pub first_event: u8,
    pub first_error: u8,
}

pub fn parse_query_extension(f: &[u8]) -> Option<QueryExtensionReply> {
    if f.len() < 32 {
        return None;
    }
    Some(QueryExtensionReply {
        present: f[8] != 0,
        major_opcode: f[9],
        first_event: f[10],
        first_error: f[11],
    })
}

pub fn parse_list_extensions(f: &[u8]) -> Option<Vec<String>> {
    if f.len() < 32 {
        return None;
    }
    let count = f[1] as usize;
    let mut names = Vec::with_capacity(count);
    let mut o = 32;
    for _ in 0..count {
        let len = *f.get(o)? as usize;
        let name = f.get(o + 1..o + 1 + len)?;
        names.push(String::from_utf8_lossy(name).into_owned());
        o += 1 + len;
    }
    Some(names)
}

pub struct XfixesVersionReply {
    pub major: u32,
    pub minor: u32,
}

pub fn parse_xfixes_query_version(f: &[u8]) -> Option<XfixesVersionReply> {
    if f.len() < 32 {
        return None;
    }
    Some(XfixesVersionReply { major: u32at(f, 8), minor: u32at(f, 12) })
}

pub struct PictFormat {
    pub id: u32,
    pub ty: u8,
    pub depth: u8,
    pub alpha_shift: u16,
    pub alpha_mask: u16,
}

// only the format table; the per-screen tail isn't needed to pick argb32
pub fn parse_render_query_pict_formats(f: &[u8]) -> Option<Vec<PictFormat>> {
    if f.len() < 32 {
        return None;
    }
    let count = u32at(f, 8) as usize;
    let mut out = Vec::with_capacity(count);
    let mut o = 32;
    for _ in 0..count {
        let rec = f.get(o..o + 28)?;
        out.push(PictFormat {
            id: u32at(rec, 0),
            ty: rec[4],
            depth: rec[5],
            alpha_shift: u16at(rec, 20),
            alpha_mask: u16at(rec, 22),
        });
        o += 28;
    }
    Some(out)
}

pub struct ClientIdValue {
    pub client: u32,
    pub mask: u32,
    pub values: Vec<u32>,
}

pub fn parse_res_query_client_ids(f: &[u8]) -> Option<Vec<ClientIdValue>> {
    if f.len() < 32 {
        return None;
    }
    let count = u32at(f, 8) as usize;
    let mut out = Vec::with_capacity(count);
    let mut o = 32;
    for _ in 0..count {
        let head = f.get(o..o + 12)?;
        let len_bytes = u32at(head, 8) as usize;
        let mut values = Vec::with_capacity(len_bytes / 4);
        let body = f.get(o + 12..o + 12 + len_bytes)?;
        for c in body.chunks_exact(4) {
            values.push(u32::from_ne_bytes([c[0], c[1], c[2], c[3]]));
        }
        out.push(ClientIdValue { client: u32at(head, 0), mask: u32at(head, 4), values });
        o += 12 + len_bytes;
    }
    Some(out)
}

// -- errors --

pub struct XError {
    pub code: u8,
    pub sequence: u16,
    pub bad_value: u32,
    pub minor: u16,
    pub major: u8,
}

pub fn parse_error(f: &[u8]) -> Option<XError> {
    if f.len() < 32 || f[0] != 0 {
        return None;
    }
    Some(XError {
        code: f[1],
        sequence: u16at(f, 2),
        bad_value: u32at(f, 4),
        minor: u16at(f, 8),
        major: f[10],
    })
}

pub fn error_name(code: u8) -> &'static str {
    match code {
        1 => "Request",
        2 => "Value",
        3 => "Window",
        4 => "Pixmap",
        5 => "Atom",
        6 => "Cursor",
        7 => "Font",
        8 => "Match",
        9 => "Drawable",
        10 => "Access",
        11 => "Alloc",
        12 => "Colormap",
        13 => "GContext",
        14 => "IDChoice",
        15 => "Name",
        16 => "Length",
        17 => "Implementation",
        _ => "Unknown",
    }
}

// -- events --

#[derive(Debug)]
pub enum XEvent {
    CreateNotify {
        parent: u32,
        window: u32,
        x: i16,
        y: i16,
        width: u16,
        height: u16,
        border_width: u16,
        override_redirect: bool,
    },
    DestroyNotify {
        event: u32,
        window: u32,
    },
    UnmapNotify {
        event: u32,
        window: u32,
        from_configure: bool,
    },
    MapNotify {
        event: u32,
        window: u32,
        override_redirect: bool,
    },
    MapRequest {
        parent: u32,
        window: u32,
    },
    ConfigureNotify {
        event: u32,
        window: u32,
        above_sibling: u32,
        x: i16,
        y: i16,
        width: u16,
        height: u16,
        border_width: u16,
        override_redirect: bool,
    },
    ConfigureRequest {
        stack_mode: u8,
        parent: u32,
        window: u32,
        sibling: u32,
        x: i16,
        y: i16,
        width: u16,
        height: u16,
        border_width: u16,
        value_mask: u16,
    },
    PropertyNotify {
        window: u32,
        atom: u32,
        time: u32,
        state: u8,
    },
    FocusIn {
        detail: u8,
        event: u32,
        mode: u8,
    },
    SelectionRequest {
        time: u32,
        owner: u32,
        requestor: u32,
        selection: u32,
        target: u32,
        property: u32,
    },
    SelectionNotify {
        time: u32,
        requestor: u32,
        selection: u32,
        target: u32,
        property: u32,
    },
    XfixesSelectionNotify {
        subtype: u8,
        window: u32,
        owner: u32,
        selection: u32,
        timestamp: u32,
        selection_timestamp: u32,
    },
    ClientMessage {
        format: u8,
        window: u32,
        ty: u32,
        data: [u32; 5],
    },
}

// the top bit marks send_event frames and is ignored here
pub fn parse_event(f: &[u8], xfixes_first_event: u8) -> Option<XEvent> {
    if f.len() < 32 {
        return None;
    }
    let code = f[0] & 0x7f;
    if xfixes_first_event != 0 && code == xfixes_first_event {
        return Some(XEvent::XfixesSelectionNotify {
            subtype: f[1],
            window: u32at(f, 4),
            owner: u32at(f, 8),
            selection: u32at(f, 12),
            timestamp: u32at(f, 16),
            selection_timestamp: u32at(f, 20),
        })
;
    }
    match code {
        33 => Some(XEvent::ClientMessage {
            format: f[1],
            window: u32at(f, 4),
            ty: u32at(f, 8),
            data: [
                u32at(f, 12),
                u32at(f, 16),
                u32at(f, 20),
                u32at(f, 24),
                u32at(f, 28),
            ],
        }),
        16 => {
            Some(XEvent::CreateNotify {
                parent: u32at(f, 4),
                window: u32at(f, 8),
                x: i16at(f, 12),
                y: i16at(f, 14),
                width: u16at(f, 16),
                height: u16at(f, 18),
                border_width: u16at(f, 20),
                override_redirect: f[22] != 0,
            })
        }
        17 => {
            Some(XEvent::DestroyNotify {
                event: u32at(f, 4),
                window: u32at(f, 8),
            })
        }
        18 => {
            Some(XEvent::UnmapNotify {
                event: u32at(f, 4),
                window: u32at(f, 8),
                from_configure: f[12] != 0,
            })
        }
        19 => {
            Some(XEvent::MapNotify {
                event: u32at(f, 4),
                window: u32at(f, 8),
                override_redirect: f[12] != 0,
            })
        }
        20 => {
            Some(XEvent::MapRequest {
                parent: u32at(f, 4),
                window: u32at(f, 8),
            })
        }
        22 => {
            Some(XEvent::ConfigureNotify {
                event: u32at(f, 4),
                window: u32at(f, 8),
                above_sibling: u32at(f, 12),
                x: i16at(f, 16),
                y: i16at(f, 18),
                width: u16at(f, 20),
                height: u16at(f, 22),
                border_width: u16at(f, 24),
                override_redirect: f[26] != 0,
            })
        }
        23 => {
            Some(XEvent::ConfigureRequest {
                stack_mode: f[1],
                parent: u32at(f, 4),
                window: u32at(f, 8),
                sibling: u32at(f, 12),
                x: i16at(f, 16),
                y: i16at(f, 18),
                width: u16at(f, 20),
                height: u16at(f, 22),
                border_width: u16at(f, 24),
                value_mask: u16at(f, 26),
            })
        }
        28 => {
            Some(XEvent::PropertyNotify {
                window: u32at(f, 4),
                atom: u32at(f, 8),
                time: u32at(f, 12),
                state: f[16],
            })
        }
        9 => {
            Some(XEvent::FocusIn {
                detail: f[1],
                event: u32at(f, 4),
                mode: f[8],
            })
        }
        30 => {
            Some(XEvent::SelectionRequest {
                time: u32at(f, 4),
                owner: u32at(f, 8),
                requestor: u32at(f, 12),
                selection: u32at(f, 16),
                target: u32at(f, 20),
                property: u32at(f, 24),
            })
        }
        31 => {
            Some(XEvent::SelectionNotify {
                time: u32at(f, 4),
                requestor: u32at(f, 8),
                selection: u32at(f, 12),
                target: u32at(f, 16),
                property: u32at(f, 20),
            })
        }
        _ => None,
    }
}

pub fn encode_client_message(window: u32, ty: u32, format: u8, data: &[u32; 5]) -> [u8; 32] {
    let mut f = [0u8; 32];
    f[0] = 33;
    f[1] = format;
    f[4..8].copy_from_slice(&window.to_ne_bytes());
    f[8..12].copy_from_slice(&ty.to_ne_bytes());
    for (i, d) in data.iter().enumerate() {
        f[12 + i * 4..16 + i * 4].copy_from_slice(&d.to_ne_bytes());
    }
    f
}

// synthetic answer for a ConfigureRequest we won't grant; event=window
pub fn encode_configure_notify(window: u32, x: i16, y: i16, w: u16, h: u16, border: u16) -> [u8; 32] {
    let mut f = [0u8; 32];
    f[0] = 22;
    f[4..8].copy_from_slice(&window.to_ne_bytes());
    f[8..12].copy_from_slice(&window.to_ne_bytes());
    // above_sibling stays None
    f[16..18].copy_from_slice(&x.to_ne_bytes());
    f[18..20].copy_from_slice(&y.to_ne_bytes());
    f[20..22].copy_from_slice(&w.to_ne_bytes());
    f[22..24].copy_from_slice(&h.to_ne_bytes());
    f[24..26].copy_from_slice(&border.to_ne_bytes());
    f
}

pub fn encode_selection_notify(
    time: u32,
    requestor: u32,
    selection: u32,
    target: u32,
    property: u32,
) -> [u8; 32] {
    let mut f = [0u8; 32];
    f[0] = 31;
    f[4..8].copy_from_slice(&time.to_ne_bytes());
    f[8..12].copy_from_slice(&requestor.to_ne_bytes());
    f[12..16].copy_from_slice(&selection.to_ne_bytes());
    f[16..20].copy_from_slice(&target.to_ne_bytes());
    f[20..24].copy_from_slice(&property.to_ne_bytes());
    f
}

// -- the setup handshake --

pub fn encode_setup_request(b: &mut Vec<u8>, auth_name: &[u8], auth_data: &[u8]) {
    b.push(if cfg!(target_endian = "little") { 0x6c } else { 0x42 });
    b.push(0);
    b.extend_from_slice(&11u16.to_ne_bytes());
    b.extend_from_slice(&0u16.to_ne_bytes());
    b.extend_from_slice(&(auth_name.len() as u16).to_ne_bytes());
    b.extend_from_slice(&(auth_data.len() as u16).to_ne_bytes());
    b.extend_from_slice(&[0u8; 2]);
    b.extend_from_slice(auth_name);
    while b.len() % 4 != 0 {
        b.push(0);
    }
    b.extend_from_slice(auth_data);
    while b.len() % 4 != 0 {
        b.push(0);
    }
}

// the first 8 bytes say how much more to read
pub fn setup_reply_len(prefix: &[u8]) -> Option<usize> {
    if prefix.len() < 8 {
        return None;
    }
    Some(u16at(prefix, 6) as usize * 4)
}

pub struct SetupScreen {
    pub root: u32,
    pub root_visual: u32,
    pub root_depth: u8,
    pub width: u16,
    pub height: u16,
}

pub struct Setup {
    pub resource_id_base: u32,
    pub resource_id_mask: u32,
    pub screens: Vec<SetupScreen>,
}

// f is the full reply including the 8 byte prefix; success must be 1
pub fn parse_setup(f: &[u8]) -> Option<Setup> {
    if f.len() < 40 || f[0] != 1 {
        return None;
    }
    let base = u32at(f, 12);
    let mask = u32at(f, 16);
    let vendor_len = u16at(f, 24) as usize;
    let n_screens = f[28] as usize;
    let n_formats = f[29] as usize;
    let mut o = 40 + vendor_len.div_ceil(4) * 4 + n_formats * 8;
    let mut screens = Vec::with_capacity(n_screens);
    for _ in 0..n_screens {
        let s = f.get(o..o + 40)?;
        screens.push(SetupScreen {
            root: u32at(s, 0),
            root_visual: u32at(s, 32),
            root_depth: s[38],
            width: u16at(s, 20),
            height: u16at(s, 22),
        });
        let n_depths = s[39] as usize;
        o += 40;
        for _ in 0..n_depths {
            let d = f.get(o..o + 8)?;
            let n_visuals = u16at(d, 2) as usize;
            o += 8 + n_visuals * 24;
        }
    }
    Some(Setup { resource_id_base: base, resource_id_mask: mask, screens })
}

#[cfg(test)]
mod freshness {
    use sha2::{Digest, Sha256};

    // pins tools/gen-xwire/src/main.rs as of the last regeneration
    const GEN_SRC_HASH: &str = "d231c197e75099073e65ca7fa0ed2cc96ae2a7ba85d786f3eaa52671d4bb709e";
    const REGEN: &str =
        "x11 wire codecs out of date - rerun: cargo run --manifest-path tools/gen-xwire/Cargo.toml";

    #[test]
    fn generator_matches_committed_codecs() {
        let gen_src = include_str!("../../tools/gen-xwire/src/main.rs");
        let hash: String = Sha256::digest(gen_src.as_bytes())
            .iter()
            .map(|b| format!("{b:02x}"))
            .collect();
        assert_eq!(GEN_SRC_HASH, hash, "{REGEN}");
    }
}
